### ISSUE TITLE
Unable to get chat from replays

### ISSUE THREAD

**Issue by MaverickEsq** [Aimdrol/WoT-Replay-Analyzer#1]
`// I'm sure it is known and discussed on the forum page, however as an NA user I cannot access the EU forums and making a whole new account seems silly when I have git. I figure it easier for me to make bug reports here and also I will be alerted if they're fixed.`

## Description of issue

Attempting to pull the chat log from a replay will make the client go into the processing screen and attempt to process it before dumping you back in the main view. Thereafter the log contains L1.

This is true of every replay at least of the current version (9.18.0). I tested 5 random replays.

Attempting to save to file has the same errors and a second error from the stripping of html if the strip html option is selected or if it isn't. As shown in L2.

---

## Logs

**L1**
```
[18/05/2017-22:05:29] [Error] Could not load chat of replay <path>
[18/05/2017-22:05:29] [Error] Source: Newtonsoft.Json
[18/05/2017-22:05:29] [Error] Message: Error reading JObject from JsonReader. Path '', line 0, position 0.
[18/05/2017-22:05:29] [Error] StackTrace:
[18/05/2017-22:05:29] [Error] 01:    at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader)
[18/05/2017-22:05:29] [Error] 02:    at Newtonsoft.Json.Linq.JObject.Parse(String json)
[18/05/2017-22:05:29] [Error] 03:    at WRA.MainWindow.worker_chat_DoWork(Object sender, DoWorkEventArgs e)
[18/05/2017-22:05:29] [Error] Target Site:
[18/05/2017-22:05:29] [Error] Newtonsoft.Json.Linq.JObject Load(Newtonsoft.Json.JsonReader)
```

**L2**
```
[18/05/2017-22:22:49] [Error] Could not load chat of replay <path>
[18/05/2017-22:22:49] [Error] Source: Newtonsoft.Json
[18/05/2017-22:22:49] [Error] Message: Error reading JObject from JsonReader. Path '', line 0, position 0.
[18/05/2017-22:22:49] [Error] StackTrace:
[18/05/2017-22:22:49] [Error] 01:    at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader)
[18/05/2017-22:22:49] [Error] 02:    at Newtonsoft.Json.Linq.JObject.Parse(String json)
[18/05/2017-22:22:49] [Error] 03:    at WRA.ExportWindow.worker_chat_DoWork(Object sender, DoWorkEventArgs e)
[18/05/2017-22:22:49] [Error] Target Site:
[18/05/2017-22:22:49] [Error] Newtonsoft.Json.Linq.JObject Load(Newtonsoft.Json.JsonReader)
[18/05/2017-22:23:01] [Error] Error saving chat to file.
[18/05/2017-22:23:01] [Error] Source: Newtonsoft.Json
[18/05/2017-22:23:01] [Error] Message: Error reading JObject from JsonReader. Path '', line 0, position 0.
[18/05/2017-22:23:01] [Error] StackTrace:
[18/05/2017-22:23:01] [Error] 01:    at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader)
[18/05/2017-22:23:01] [Error] 02:    at Newtonsoft.Json.Linq.JObject.Parse(String json)
[18/05/2017-22:23:01] [Error] 03:    at WRA.ReplayExtensions.GetChat(Replay replay, Boolean removeHTMLTags)
[18/05/2017-22:23:01] [Error] 04:    at WRA.ExportWindow.ExportChat_Post()
[18/05/2017-22:23:01] [Error] Target Site:
[18/05/2017-22:23:01] [Error] Newtonsoft.Json.Linq.JObject Load(Newtonsoft.Json.JsonReader)
```

---

## My machine

**OS:** Win7 x64
**WOT version:** 9.18.0 #428
**Replay Analyzer pull date**: 18/05/2017

Don't know how much of this is helpful but hey, gotta at least try to make a sane bug report.

**Comment by Aimdrol** [comment]
Sadly there is nothing I can do about it. I'm going to have to see if some Russian modder knows more about the replay file structure.
